### ISSUE TITLE
[Enhancement] Keeping the Nav Bar Consistent

### ISSUE THREAD

**Issue by vanessasgh** [info442-aut21/d-team#81] opened 2021-11-22 17:48 UTC
I think that leaving the nav bar consistent on top might become a better usability feature for the website. Most websites tend to have it all the same, regardless of which tab they are currently on, and maybe use an inidicator(color differences / underline / etc) to show which page they're on. I think using a nav bar which just shows what other page you have besides it might make it confusing on how to reach other pages since it is always changing and the users might not realize that.

**Comment by IamSuperB4** [comment] 2021-11-24 18:11
Duplicate of #73

**Closed by IamSuperB4** 2021-11-24 18:11 UTC
Labels: duplicate, enhancement
