### ISSUE TITLE
[ Minor ] - on mobile devices, when I click through creating adventure, the cards are squished and unreadable

### ISSUE THREAD

**Issue by angelinapoltavskiy** [info442-aut21/d-team#80] opened 2021-11-22 17:38 UTC
When I opened the app on my phone , the create adventure pages have the cards squished in a row, making it difficult to read some, and unable to read others entirely
environment: safari browser, iphone XR
steps to reproduce: on a mobile device of iphone XR or smaller screen, open up you application - click through creating an adventure
expected result: the cards would be in column format on mobile through creating adventure
actual result: the cards are in a row through the create adventure - making it impossible to read some of the cards

**Comment by sershon** [comment] 2021-11-22 18:26
Additional info: The "Adventure Awaits" image is squished and the icons for the activity cards spills out as well. It would be much nicer if the icons were contained the adventure awaits image scaled to the phone screen both vertically and horizontally.
![Screenshot_20211122-095411_Chrome](https://user-images.githubusercontent.com/72484672/142915070-b70fde5b-8451-4149-ac68-b219c19beedd.jpg)

**Comment by IamSuperB4** [comment] 2021-11-24 18:10
Duplicate of #72

**Closed by IamSuperB4** 2021-11-24 18:10 UTC
