### ISSUE TITLE
[Enhancement] Add a search bar in the directory

### ISSUE THREAD

**Issue by Preciousstowers** [info442-aut21/d-team#84] opened 2021-11-22 20:49 UTC
Adding a search bar on the directory page. 

Adding a search bar in the directory would increase user-intuitiveness because it would allow users to look up specific places they might have previously been offered, instead of searching through each category and then searching through the offered locations.

**Comment by IamSuperB4** [comment] 2021-11-24 18:11
Duplicate of #75

**Closed by IamSuperB4** 2021-11-24 18:11 UTC
Labels: duplicate
